function Hd = FilterWithKaiser
%FILTERWITHKAISER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 19-Jun-2022 23:00:58

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 11025;  % Sampling Frequency

N    = 600;      % Order
Fc   = 3800;     % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 7.685;    % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
